### ISSUE TITLE
Failed to install dependencies during project setup

### ISSUE THREAD

**Issue by ananthrajsingh** [ishan-srivastava/react-seed#2]
First of all, thank you for this seed project. 

I am actually facing issue running `npm install` command. I am getting error:
```
No matching version found for navi@^2.7.1
```

Any idea what the issue could be?

**Comment by ishan-srivastava** [comment]
That's strange, can you deleted react-navi and navi from the project dependencies and run **npm install navi react-navi**,
that should have install the latest. Let me know if this works.

**Comment by ananthrajsingh** [comment]
There were these two dependencies in `package.json` for `navi`:
```
...
"navi": "^2.7.1",
...
"react-navi": "^0.14.4",
...
```

I tried removing `"navi": "^2.7.1"` and things are working fine now. Is this okay, or something might break in the future?
